# CYBEROPS Kitty
foreground              #E7FBFF
background              #050816
selection_foreground    #FFFFFF
selection_background    #252047
cursor                   #00F5FF
cursor_text_color        #050816
url_color                #00F5FF
active_border_color      #00F5FF
inactive_border_color    #34405A
bell_border_color        #FFE600

color0  #03040C
color1  #FF3147
color2  #39FF14
color3  #FFE600
color4  #2378FF
color5  #FF2D95
color6  #00F5FF
color7  #B8D8E4
color8  #34405A
color9  #FF6070
color10 #83FF6B
color11 #FFF06A
color12 #74A7FF
color13 #FF78BB
color14 #72FBFF
color15 #FFFFFF

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
background_opacity 0.94
window_padding_width 8
