mode = "dark"

accent = "#00F5FF"
selection = "#252047"
muted = "#34405A"

background = "#050816"
dark_background = "#03040C"
darker_background = "#010207"
lighter_background = "#10192B"

foreground = "#E7FBFF"
dark_foreground = "#74849C"
light_foreground = "#B8D8E4"
bright_foreground = "#FFFFFF"

hyprland_active_border = "rgba(00f5ffee) rgba(ff2d95ee) rgba(39ff14ee) 45deg"
hyprland_inactive_border = "rgba(34405aaa)"

red = "#FF3147"
yellow = "#FFE600"
orange = "#FF7E00"
green = "#39FF14"
cyan = "#00F5FF"
blue = "#2378FF"
magenta = "#FF2D95"
brown = "#7A5168"

bright_red = "#FF6070"
bright_yellow = "#FFF06A"
bright_green = "#83FF6B"
bright_cyan = "#72FBFF"
bright_blue = "#74A7FF"
bright_magenta = "#FF78BB"
